#!/bin/bash

echo "*******************************"
echo "** Package Installed:"
echo "** NodeJS: $(node -v)"
echo "** npm: $(npm -v)" 
echo "** Python3: $(python3 -V)"
echo "** Python: $(python -V)"
echo "** pip3: $(pip3 -V)"
echo "** sam: $(sam --version)"
echo "*******************************"